version: '2'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
